### ISSUE TITLE
Incompatibility with Static.jl v1 is causing package resolution problems

### ISSUE THREAD

**Issue by korsbo** [chengchingwen/NeuralAttentionlib.jl#33]
Hi, as mentioned in #32, the incompatibility of this package with Static.jl v1 is causing some package resolution problems for certain applications. I see from the failing CI of #32 that it's not sufficient with a trivial bump of the compat list but I have not looked deep enough to understand the extent of the update required.

**Comment by chengchingwen** [comment]
It seems Static.jl v1 is not relevant to the failing CI which failed to infer the return type of some rrule, so I merged it directly. I'll try if I can find the correct cause that silently messes up the type inference, if not, I will disable those checks and make a release these days.

**Comment by chengchingwen** [comment]
The CI fail is caused by ChainRulesCore.jl v1.25.1 (see https://github.com/JuliaDiff/ChainRulesCore.jl/issues/684).

**Comment by johannes-fischer** [comment]
Could you tag and register a new version? Currently it still doesn't work if you just `]add Transformers` to a workspace that requires Static.jl v1.0, since the merged change is not in a registered version of this package. So it still requires to add `NeuralAttentionlib#master`.

**Comment by chengchingwen** [comment]
tagged
